/*
 * This source file was generated by the Gradle 'init' task
 */
package citi_stock_app;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasRunningLogic() {
        // Simple placeholder test
        assertNotNull("Citi Dashboard", "Citi Dashboard");
    }
}